Repository HS-Continuity/Mobile, pull requests merged in 2024-08, with the labels that each got.

#40 KAN-686 fix: 로그인 디자인 수정
  .gitignore
  src/App.jsx
  src/apis/index.js
  src/assets/icon/apple.png
  src/assets/icon/bento.png
  src/assets/icon/broccoli.png
  src/assets/icon/egg.png
  src/assets/icon/fish.png
  src/assets/icon/green.png
  src/assets/icon/mate.png
  src/assets/icon/meat.png
  src/assets/icon/milk.png
  src/assets/icon/rice.png
  src/assets/icon/seed.png
  src/components/Layouts/CategoryData.jsx
  src/components/Order/CardRegisterModal.jsx
  src/components/Order/Payment.jsx
  src/components/Product/ProductItem.jsx
  src/components/Product/ProductList.jsx
  src/main.jsx
  src/pages/cart/index.jsx
  src/pages/error/NotFound.jsx
  src/pages/home/ProductSlider.jsx
  src/pages/login/index.jsx
  src/pages/order/index.jsx
  src/pages/payment/index.jsx
  src/pages/signup/index.jsx
  src/pages/subscriptionOrder/SubscriptionOrder.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx
  src/stores/useAuthStore.js
Labels: API, HTML+CSS, Refactor

#41 KAN-694 feat: 회원가입 중복 검사
  src/apis/index.js
  src/components/Product/ProductItem.jsx
  src/pages/address/index.jsx
  src/pages/login/index.jsx
  src/pages/payment/index.jsx
  src/pages/review/ReviewApply.jsx
  src/pages/signup/index.jsx
Labels: Feature, Refactor

#42 KAN-717 feat: Skeleton 및 error 컴포넌트설정
  src/apis/axiosConfig.js
  src/components/Errors/ErrorDisplay.jsx
  src/components/Layouts/BottomNav.jsx
  src/components/Layouts/CategoryMenu.jsx
  src/components/Layouts/PopularKeywords.jsx
  src/components/Login/LoginLayout.jsx
  src/components/Order/AddressEditModal.jsx
  src/components/Order/AddressModal.jsx
  src/components/Order/AddressRegisterModal.jsx
  src/components/Order/CardEditModal.jsx
  src/components/Order/CardRegisterModal.jsx
  src/components/Order/ConsentPayment.jsx
  src/components/Order/DeliveryAddress.jsx
  src/components/Order/DeliveryMemo.jsx
  src/components/Order/MemberCouponList.jsx
  src/components/Order/OrderItems.jsx
  src/components/Order/OrderMemberInfo.jsx
  src/components/Order/OrderPrice.jsx
  src/components/Order/Payment.jsx
  src/components/Order/SubscriptionInfo.jsx
  src/components/Product/AdvertisementProductList.jsx
  src/components/Product/ProductList.jsx
  src/components/Product/ReviewAllList.jsx
  src/components/Skeletons/MypageSkeleton.jsx
  src/components/Skeletons/OrderDetailSkeleton.jsx
  src/components/Skeletons/OrderListSkeleton.jsx
  src/components/Skeletons/PaymentSkeleton.jsx
  src/components/Skeletons/PopularKeywordsSkeleton.jsx
  src/components/Skeletons/ProductDetailSkeleton.jsx
  src/components/Skeletons/ProductSliderSkeleton.jsx
  src/components/Skeletons/ProfileSkeleton.jsx
  src/components/Skeletons/ShopSkeleton.jsx
  src/components/Skeletons/SubscriptionOrderDetailSkeleton.jsx
  src/components/Skeletons/SubscriptionOrderListSkeleton.jsx
  src/components/Toast/ToastDisplay.jsx
  src/pages/address/index.jsx
  src/pages/cart/index.jsx
  src/pages/coupon/index.jsx
  src/pages/home/CategoryGrid.jsx
  src/pages/login/index.jsx
  src/pages/memberInfo/index.jsx
  src/pages/order/OrderSuccess.jsx
  src/pages/order/index.jsx
  src/pages/orderManage/OrderDetail.jsx
  src/pages/orderManage/OrderList.jsx
  src/pages/orderManage/RefundApply.jsx
  src/pages/payment/index.jsx
  src/pages/product/index.jsx
  src/pages/review/index.jsx
  src/pages/search/index.jsx
  src/pages/shop/index.jsx
  src/pages/subscriptionOrder/SubscriptionOrder.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx
  src/pages/timeSale/timeSaleDetail.jsx
  src/pages/timeSale/timeSaleList.jsx
Labels: Refactor

#43 KAN-718 style: 슬라이더 수정 및 사소한 디자인 변경
  src/App.css
  src/apis/apiUtils.js
  src/apis/index.js
  src/assets/images/eco_food.jpg
  src/assets/images/general_food.jpg
  src/assets/images/general_food1.jpg
  src/assets/images/jung.png
  src/assets/images/kim.png
  src/assets/images/ku.jpg
  src/assets/images/kwon.png
  src/assets/images/timesale.jpg
  src/components/Order/MaskDigits.jsx
  src/components/Product/CountdownTimer.module.css
  src/components/Product/ProductItem.jsx
  src/components/Skeletons/CartSkeleton.jsx
  src/components/Skeletons/CategorySkeleton.jsx
  src/components/Skeletons/CouponSkeleton.jsx
  src/components/Skeletons/FetchingNextSkeleton.jsx
  src/pages/eco/index.jsx
  src/pages/general/index.jsx
  src/pages/home/ProductSlider.jsx
  src/pages/memberInfo/MenuItems.jsx
  src/pages/memberInfo/Profile.jsx
  src/pages/order/OrderFail.jsx
  src/pages/review/ReviewApply.jsx
  src/pages/search/SearchResult.jsx
  src/pages/signup/index.jsx
  src/pages/subscriptionOrder/SubscriptionSetup.jsx
  src/pages/timeSale/index.jsx
  src/stores/useAuthStore.js
Labels: HTML+CSS, Refactor

#53 KAN-730 fix: 버그 디자인 수정
  src/apis/index.js
  src/assets/images/kim.jpg
  src/components/Layouts/CategoryData.jsx
  src/components/Layouts/Main.jsx
  src/components/Order/OrderHeader.jsx
  src/components/Order/OrderItems.jsx
  src/components/Product/FallbackProduct.jsx
  src/pages/cart/index.jsx
  src/pages/home/ProductSlider.jsx
  src/pages/orderManage/OrderDetail.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx
  src/pages/timeSale/timeSaleDetail.jsx
Labels: BugFix, HTML+CSS, Refactor

#56 KAN-741 feat: 카테고리 페이지 구현
  src/App.jsx
  src/apis/index.js
  src/components/Layouts/CategoryData.jsx
  src/components/Layouts/CategoryMenu.jsx
  src/components/Product/CategoryProductItem.jsx
  src/components/Product/CategoryProductList.jsx
  src/pages/home/CategoryGrid.jsx
  src/pages/home/ProductSlider.jsx
  src/pages/order/index.jsx
  src/pages/product/Category.jsx
  src/pages/product/DetailCategory.jsx
Labels: Feature, API, HTML+CSS

#58 KAN-745 fix: 내용 디자인 수정
  src/apis/index.js
  src/components/Login/ProtectedRoute.jsx
  src/components/Order/GetStatusText.jsx
  src/components/Order/Payment.jsx
  src/pages/cart/index.jsx
  src/pages/home/ProductSlider.jsx
  src/pages/memberInfo/MypageMenu.jsx
  src/pages/order/index.jsx
  src/pages/shop/index.jsx
  src/pages/subscriptionOrder/SubscriptionOrder.jsx
  src/pages/subscriptionOrder/SubscriptionSetup.jsx
Labels: Feature, API, HTML+CSS

#57 KAN-742 feat: 주문 및 정기주문 페이지 상품서비스 불가 화면 구성
  src/pages/orderManage/OrderDetail.jsx
  src/pages/orderManage/OrderList.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx
Labels: BugFix, Refactor

#59 KAN-747 refactor: 주석 출력 삭제
  src/App.jsx
  src/apis/apiUtils.js
  src/apis/index.js
  src/assets/data/1.jpg
  src/assets/data/10.jpg
  src/assets/data/11.jpg
  src/assets/data/12.jpg
  src/assets/data/13.png
  src/assets/data/14.jpg
  src/assets/data/15.jpg
  src/assets/data/16.jpg
  src/assets/data/17.jpg
  src/assets/data/18.jpg
  src/assets/data/19.jpg
  src/assets/data/2.jpg
  src/assets/data/20.jpg
  src/assets/data/3.jpg
  src/assets/data/4.jpg
  src/assets/data/5.jpg
  src/assets/data/6.jpg
  src/assets/data/7.jpg
  src/assets/data/8.jpg
  src/assets/data/9.jpg
  src/components/Layouts/PopularKeywordTicker.jsx
  src/components/Layouts/RecentSearches.jsx
  src/components/Layouts/TopHeader.jsx
  src/components/Order/AddAddressModal.jsx
  src/components/Order/CardEditModal.jsx
  src/components/Order/CardRegisterModal.jsx
  src/components/Order/OrderHeader.jsx
  src/components/Order/OrderItems.jsx
  src/components/Product/AdvertisementProductList.jsx
  src/components/Product/CategoryProductList.jsx
  src/components/Product/FallbackProduct.jsx
  src/components/Product/ProductList.jsx
  src/main.jsx
  src/pages/cart/index.jsx
  src/pages/eco/index.jsx
  src/pages/home/CategoryGrid.jsx
  src/pages/login/index.jsx
  src/pages/memberInfo/Profile.jsx
  src/pages/order/index.jsx
  src/pages/orderManage/RefundApply.jsx
  src/pages/product/Category.jsx
  src/pages/product/DetailCategory.jsx
  src/pages/signup/index.jsx
  src/pages/subscriptionOrder/SubscriptionOrder.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderManage.jsx
  src/pages/timeSale/timeSaleDetail.jsx
  src/pages/timeSale/timeSaleItem.jsx
  src/stores/useAuthStore.js
  src/stores/useCartStore.js
Labels: Refactor

#65 KAN-752 fix정기주문 스크롤버그 해결
  src/pages/product/DetailCategory.jsx
  src/pages/subscriptionOrder/SubscriptionOrder.jsx
Labels: BugFix

#66 모바일 연이음 페이지 (v1.7)
  src/pages/product/DetailCategory.jsx
  src/pages/subscriptionOrder/SubscriptionOrder.jsx
  src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx
Labels: Deploy
